export const GET_TOKEN = 'GET_TOKEN';
export const GET_TOKEN_SUCCESS = 'GET_TOKEN_SUCCESS';
export const GET_TOKEN_FAIL = 'GET_TOKEN_FAIL';

export const GET_CINEMAS = 'GET_CINEMAS';
export const GET_CINEMAS_SUCCESS = 'GET_CINEMAS_SUCCESS';
export const GET_CINEMAS_FAIL = 'GET_CINEMAS_FAIL';

export const GET_CINEMA_MOVIES = 'GET_CINEMA_MOVIES';
export const GET_CINEMA_MOVIES_SUCCESS = 'GET_CINEMA_MOVIES_SUCCESS';
export const GET_CINEMA_MOVIES_FAIL = 'GET_CINEMA_MOVIES_FAIL';

export const GET_ALL_MOVIES = 'GET_ALL_MOVIES';
export const GET_ALL_MOVIES_SUCCESS = 'GET_ALL_MOVIES_SUCCESS';
export const GET_ALL_MOVIES_FAIL = 'GET_ALL_MOVIES_FAIL';

export const GET_UPCOMING_MOVIES = 'GET_UPCOMING_MOVIES';
export const GET_UPCOMING_MOVIES_SUCCESS = 'GET_UPCOMING_MOVIES_SUCCESS';
export const GET_UPCOMING_MOVIES_FAIL = 'GET_UPCOMING_MOVIES_FAIL';